### ISSUE TITLE
Uploading Flaps Gerbers to JLCPCB

### ISSUE THREAD

**Issue by joelhauxwell** [ToonVanEyck/OpenFlap#2]
Hey ToonVanEyck,

I know the project landing page for this warns against building anything just yet but i would really like to build some of your amazing modules.

I have tried to upload one of the flap gerber zips to JLCPCB but there seems to be an issue with the file.  It opens in the Gerber Preview pane with errors:

![image](https://github.com/ToonVanEyck/OpenFlap/assets/71120697/fe370aee-4af1-4085-9c1c-d45a53d3656f)

And in the main order page, the size isn't detected:

![image](https://github.com/ToonVanEyck/OpenFlap/assets/71120697/ee0a7b96-91a3-4c18-a229-43966aec62cb)

I could enter the dims manually and select the option for 'confirm production file' -  did you also have to do this?

If you think that me embarking on this project is a terrible idea then please let me know!

Thanks,

Joel.

**Comment by ToonVanEyck** [comment]
Hi Joel, JLC pcb seems to have these issues when the Gerber files don't contain anything on the copper layers of the Gerbers. Please let me check if all the latest Gerbers are on GitHub. I will try to update them this weekend. I will also try to write a small manual this weekend.

**Comment by ToonVanEyck** [comment]
Hi Joel,

I updated all production files as well as the README. The readme now includes all additional parts you will need as well as all the tools required. 
You will also find some additional info for ordering the flaps and encoder wheels on JLCPCB in the readme.
If you have any more questions/issues, don't hesitate to ask them through GitHub issues. 

Regards,
Toon
