### ISSUE TITLE
Fusion 360 Links Unauthorized

### ISSUE THREAD

**Issue by joelhauxwell** [ToonVanEyck/OpenFlap#3]
Hey ToonVanEyck,

I can't see the Encoder PCB in the production gerber files and using the Eagle link results in an error - 

![image](https://github.com/ToonVanEyck/OpenFlap/assets/71120697/b9b86919-7554-4c62-b078-a51b6530edf0)

Please could you upload the production files for the encoder wheels when you get a chance?

Thanks,

Joel.

**Comment by ToonVanEyck** [comment]
I have removed the links in favour of eagle .sch and .brd files
