### ISSUE TITLE
Alternative for optical sensor

### ISSUE THREAD

**Issue by joelhauxwell** [ToonVanEyck/OpenFlap#4]
Hey,

The optical sensor in the BOM is out of stock at LCSC without a date.

This looks like an appropriate alternative - https://www.lcsc.com/product-detail/Reflective-Optical-Interrupters_Everlight-Elec-ITR8307-S17-TR8-B_C81632.html 

What you do think?

Thanks,

Joel.

**Comment by ToonVanEyck** [comment]
Seems like it should work. It's cheaper too, so good catch!
